name: C/C++ CI

on:
  push:
    branches: [ master, job_points ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt -y install libssl-dev luajit lua5.1 liblua5.1-dev libzmq3-dev autoconf pkg-config gcc build-essential lua-bitop
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
